version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
      build: config
      restart: always
      ports:
        - 8888:8888

  gateway:
      build: gateway
      restart: always
      ports:
       - 5000:5000

  registry:
      build: registry
      restart: always
      ports:
        - 8761:8761

  user-service:
        build: musicroutine-user-service
        restart: always
        ports:
          - 3000:3000


