version: '2'


services:
  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=test
      - DB_PASS=123
      - DB_NAME=musicroutine

    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  user-service:
    build: musicroutine-user-service
    restart: always
    ports:
       - 8761:8761
