version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=test
      - DB_PASS=123
      - DB_NAME=musicroutine

    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql


  config:
      build: config
      restart: always
      ports:
        - 8888:8888

  gateway:
      build: gateway
      ports:
       - 81:5000


  registry:
      build: registry
      restart: always
      ports:
        - 8761:8761

  user-service:
        build: musicroutine-user-service
        restart: always
        ports:
          - 3000:3000

  routine-service:
        build: musicroutine-routine-service
        restart: always
        ports:
          - 4000:4000

  monitoring:
      build: monitoring
      restart: always
      ports:
       - 9000:8080
       - 8989:8989

