eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false

server:
  port: 5000


zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    user-service:
      path: /api/v1/user/**
      serviceId: USER-SERVICE
      url: http://user-service:3000